[shell]
program = "/home/michael/tmux-starter"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono NF"
style = "JetBrainsMono NF"

[scrolling]
history = 10000

[window]
title = "Alacritty"
startup_mode = "Maximized"
opacity = 0.8
decorations = "None"

[window.dimensions]
columns = 0
lines = 0
